#
# Golang CI pipeline configuration
#
# To execute linters in local the ./scripts/lint.sh script can be used.

linters:
  disable-all: true

  # Run golangci-lint linters to see
  enable:
    - deadcode
    - errcheck
    - goconst
    - goimports
    - golint
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - structcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    # - wsl Could be interesting but need a lot of changes

linters-settings:
  goconst:
    min-len: 5

issues:
  exclude:

  exclude-rules:
    - path: _test\.go
      linters:
        - stylecheck
        - gosec

    - path: internal/tabwriter
      linters:
        - unused
        - errcheck
