#
# Golang CI pipeline configuration
#
# To execute linters in local the ./scripts/lint.sh script can be used.

run:
  skip-dirs:
    - internal/pkg

linters:
  disable-all: true

  # Run golangci-lint linters to see the list of all linters
  # Please keep them sorted alphabetically
  enable:
    - bodyclose
    - dogsled
    - errcheck
    - goconst
    - goimports
    - goprintffuncname
    - gosec
    - gosimple
    - govet
    - ineffassign
    - misspell
    - nakedret
    - nolintlint
    - revive
    - rowserrcheck
    - staticcheck
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - whitespace

linters-settings:
  goconst:
    min-len: 5

issues:
  exclude:

  exclude-rules:
    - path: _test\.go
      linters:
        - stylecheck
        - gosec

    # Organization ID is mark as deprecated in the SDK
    # This rule ignore this deprecation
    - path: internal/namespaces/instance
      linters:
        - staticcheck
      text: "SA1019:.*Organization"

    - path: internal/tabwriter
      linters:
        - unused
        - errcheck
