name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  homebrew:
    needs:
      - goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Bump scw Homebrew formula
        uses: dawidd6/action-homebrew-bump-formula@v3
        with:
          token: ${{secrets.SCALEWAY_BOT_TOKEN}}
          formula: scw

  wasm:
    runs-on: ubuntu-latest
    needs:
      - goreleaser
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21'
      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6.0.2
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
      - name: Build
        run: VERSION=${{ github.ref_name }} ./scripts/build-wasm.sh
      - name: Configure package version
        working-directory: wasm
        run: pnpm version ${{ github.ref_name }}
      - run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_AUTH_TOKEN}"
        env:
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      - name: Publish package
        working-directory: wasm
        run: pnpm publish --no-git-checks
