name: Tests

on:
  pull_request:

jobs:
  os-tests:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - run:
        name: Run unit tests
        command: go test -v ./...
    - run: # Test the runtime for potential panics.
        name: Execute main binary
        command: go run cmd/scw/main.go -h

  build-tests:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x]
        platform: [ubuntu-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: Build binaries
        run: ./scripts/build.sh
